jobs:
  - name: dv-man
    type: manifest
    steps:
      - GET: dv-image
        pull: false
      - GET: trigger-dv-man

  - name: dv-test
    type: ecsDeploy
    steps:
      - GET: dv-man
      - GET: env-test
    on_failure:
      - uname -a
      - sgkjndfgd
